//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.ProgramsToInstall
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class ProgramsToInstall { }
#else

	public class ProgramsToInstall : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public ProgramsToInstall()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/InstallQueuer;component/SampleData/ProgramsToInstall/ProgramsToInstall.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private ProgramsList _ProgramsList = new ProgramsList();

		public ProgramsList ProgramsList
		{
			get
			{
				return this._ProgramsList;
			}
		}
	}

	public class ProgramsListItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _FilePath = string.Empty;

		public string FilePath
		{
			get
			{
				return this._FilePath;
			}

			set
			{
				if (this._FilePath != value)
				{
					this._FilePath = value;
					this.OnPropertyChanged("FilePath");
				}
			}
		}

		private string _UserFriendlyDescription = string.Empty;

		public string UserFriendlyDescription
		{
			get
			{
				return this._UserFriendlyDescription;
			}

			set
			{
				if (this._UserFriendlyDescription != value)
				{
					this._UserFriendlyDescription = value;
					this.OnPropertyChanged("UserFriendlyDescription");
				}
			}
		}

		private System.Windows.Media.ImageSource _Icon = null;

		public System.Windows.Media.ImageSource Icon
		{
			get
			{
				return this._Icon;
			}

			set
			{
				if (this._Icon != value)
				{
					this._Icon = value;
					this.OnPropertyChanged("Icon");
				}
			}
		}
	}

	public class ProgramsList : System.Collections.ObjectModel.ObservableCollection<ProgramsListItem>
	{ 
	}
#endif
}
